apiVersion: v1
kind: Pod
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  containers:
    - name: elastic
      image: elasticsearch:8.4.2
      ports:
        - containerPort: 9200
        - containerPort: 9300
      env:
      - name: ES_JAVA_OPTS
        value: -Xms2g -Xmx2g
      resources:
        requests:
         memory: 4Gi
        limits:
         memory: 4Gi
